### ISSUE TITLE
Documents are not retrieved with URL encoded _key

### ISSUE THREAD

**Issue by danielapoliveira** [joowani/python-arango#100] opened 2019-05-15 11:14 UTC
Since slashes are not valid as document _key values, and I need to have URLs as document _key, I was URL encoding them before assigning them as _key. However, when I was using `db.document(_id)` or `db.collection("collection-name"). get(_key)`, the functions return None. When I used `db.collection("collection-name").find({"_id": _id)`, however, the document was found. 

I'm using python 3.7, arango 3.4.4, and python-arango 4.4.0

Below is a minimal example to reproduce the issue:
``` python
from urllib.parse import quote_plus
from arango import ArangoClient

client = ArangoClient(protocol='http', host='localhost', port=8529)

sys_db = client.db('_system')
if not sys_db.has_database('test'):
    sys_db.create_database('test')
db = client.db("test")

if db.has_collection('collection1'):
    c = db.collection('collection1')
else:
    c = db.create_collection('collection1')

url_encoded = quote_plus("http://google.com")
c.insert({"_key": url_encoded})

print(db.document(f"collection1/{url_encoded}")) 
#  prints: None
print(db.collection("collection1").get(url_encoded)) 
# prints: None
print(db.collection("collection1").find({"_id": f"collection1/{url_encoded}"}).next()) 
# prints: {'_key': 'http%3A%2F%2Fgoogle.com', '_id': 'collection1/http%3A%2F%2Fgoogle.com', '_rev': '_YpqexJK---'}
```

**Comment by joowani** [comment] 2019-05-29 01:53
Hi @danielapoliveira,

I was able to reproduce the issue. I was also able to reproduce the issue using the chrome rest client. This looks like a bug on ArangoDB's side. Please open a ticket with them. I will keep this open for any updates. Thanks.

**Comment by danielapoliveira** [comment] 2019-06-23 17:55
Hi @joowani,
Looks like similar issues have been reported in https://github.com/arangodb/arangodb/issues/5885 and https://github.com/arangodb/arangodb/issues/8166.

These are still open and haven't been updated in a while. I'll follow those issues for any updates.

**Comment by joowani** [comment] 2019-08-22 12:07
Thanks for the update @danielapoliveira. Closing this as the problem is not with the client.

**Closed by joowani** 2019-08-22 12:07 UTC
