### ISSUE TITLE
KeyError: 'collections'

### ISSUE THREAD

**Issue by JannisT69** [joowani/python-arango#15] opened 2016-06-30 14:09 UTC
Hello,

everytime i try to use collection i get  the error "KeyError: 'collections'"

i.e: delete a collection

Traceback (most recent call last):
  File "B2ArangoDB.py", line 42, in <module> bastDB.delete_collection("l")
  File "C:\Python35\lib\site-packages\python_arango-2.2.0-py3.5.egg\arango\database.py", line 344, in delete_collection
  File "C:\Python35\lib\site-packages\python_arango-2.2.0-py3.5.egg\arango\database.py", line 46, in _refresh_collection_cache
  File "C:\Python35\lib\site-packages\python_arango-2.2.0-py3.5.egg\arango\database.py", line 234, in collections
KeyError: 'collections'

same error with create_colletion or retrieve collection information..

The actual action as create, delete etc is being executed but with the above error everytime.

**Comment by joowani** [comment] 2016-07-03 16:33
Closed as a duplicate of https://github.com/joowani/python-arango/issues/14

**Closed by joowani** 2016-07-03 16:33 UTC
