### ISSUE TITLE
Setting "minimun length" parameter while creating a full text index

### ISSUE THREAD

**Issue by marcelosz** [joowani/python-arango#21] opened 2016-09-22 14:22 UTC
Is it possible to add this feature to the add_fulltext_index() function?

**Comment by joowani** [comment] 2016-09-22 15:56
Hi Marcelosz,

I will take a look and get back to you.

Thanks,
Joohwan

**Comment by marcelosz** [comment] 2016-09-22 19:21
Thanks!

**Comment by joowani** [comment] 2016-09-23 03:11
Hi Marcelosz, 

Actually the minimum length is already implemented.
You just need to set the `min_length` variable on `add_fulltext_index`:

```
collection.add_fulltext_index(fields=['example'], min_length=4)
```

**Comment by joowani** [comment] 2016-09-23 14:22
I will be closing this ticket as the issue is closed. Let me know if you have any other questions!

**Closed by joowani** 2016-09-23 14:22 UTC
